export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const RESET_PASSWORD = 'RESET_PASSWORD'
export const SAVE_PASSWORD = 'SAVE_PASSWORD'
export const REGISTER = 'REGISTER'
export const TOKEN = 'TOKEN'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const LOAD_PROFILE_FAILED = 'LOAD_PROFILE_FAILED'